"""Генерирует ресурс версии Windows для PyInstaller (--version-file).

Исполняемый файл без сведений об издателе и продукте выглядит для
антивирусов подозрительнее, поэтому метаданные проставляются из VERSION.
"""
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, ROOT)

from fast_magnifier import APP_NAME, VERSION  # noqa: E402

nums = [int(x) for x in re.findall(r"\d+", VERSION)][:3]
while len(nums) < 4:
    nums.append(0)
quad = ", ".join(str(n) for n in nums)
dotted = ".".join(str(n) for n in nums)

TEMPLATE = f"""# Generated by tools/make_version_file.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({quad}),
    prodvers=({quad}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'violet2code'),
          StringStruct('FileDescription',
                       '{APP_NAME} - fast screen magnifier'),
          StringStruct('FileVersion', '{dotted}'),
          StringStruct('InternalName', 'MagnifySnap'),
          StringStruct('LegalCopyright',
                       'Copyright (c) 2026 violet2code. MIT License.'),
          StringStruct('OriginalFilename', 'MagnifySnap.exe'),
          StringStruct('ProductName', '{APP_NAME}'),
          StringStruct('ProductVersion', '{dotted}'),
          StringStruct('Comments',
                       'Free and open source: '
                       'https://github.com/violet2code/magnify-snap'),
        ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""

out = os.path.join(ROOT, "assets", "version_info.txt")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    f.write(TEMPLATE)
print(f"Version resource written for {VERSION}: {out}")
